/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BANK_H_RPCGEN
#define _BANK_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct b_credit_1_argument {
	char *arg1;
	int arg2;
};
typedef struct b_credit_1_argument b_credit_1_argument;

struct b_debit_1_argument {
	char *arg1;
	int arg2;
};
typedef struct b_debit_1_argument b_debit_1_argument;

#define BANK_PROG 0x20000001
#define BANK_V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define B_credit 1
extern  int * b_credit_1(char *, int , CLIENT *);
extern  int * b_credit_1_svc(char *, int , struct svc_req *);
#define B_debit 2
extern  int * b_debit_1(char *, int , CLIENT *);
extern  int * b_debit_1_svc(char *, int , struct svc_req *);
extern int bank_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define B_credit 1
extern  int * b_credit_1();
extern  int * b_credit_1_svc();
#define B_debit 2
extern  int * b_debit_1();
extern  int * b_debit_1_svc();
extern int bank_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_b_credit_1_argument (XDR *, b_credit_1_argument*);
extern  bool_t xdr_b_debit_1_argument (XDR *, b_debit_1_argument*);

#else /* K&R C */
extern bool_t xdr_b_credit_1_argument ();
extern bool_t xdr_b_debit_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BANK_H_RPCGEN */
