/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VBANK_H_RPCGEN
#define _VBANK_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct vb_credit_1_argument {
	char *arg1;
	int arg2;
};
typedef struct vb_credit_1_argument vb_credit_1_argument;

struct vb_debit_1_argument {
	char *arg1;
	int arg2;
};
typedef struct vb_debit_1_argument vb_debit_1_argument;

struct vb_transfer_1_argument {
	char *arg1;
	char *arg2;
	int arg3;
};
typedef struct vb_transfer_1_argument vb_transfer_1_argument;

#define VBANK_PROG 0x20000002
#define VBANK_V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define VB_credit 1
extern  int * vb_credit_1(char *, int , CLIENT *);
extern  int * vb_credit_1_svc(char *, int , struct svc_req *);
#define VB_debit 2
extern  int * vb_debit_1(char *, int , CLIENT *);
extern  int * vb_debit_1_svc(char *, int , struct svc_req *);
#define VB_transfer 3
extern  int * vb_transfer_1(char *, char *, int , CLIENT *);
extern  int * vb_transfer_1_svc(char *, char *, int , struct svc_req *);
extern int vbank_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define VB_credit 1
extern  int * vb_credit_1();
extern  int * vb_credit_1_svc();
#define VB_debit 2
extern  int * vb_debit_1();
extern  int * vb_debit_1_svc();
#define VB_transfer 3
extern  int * vb_transfer_1();
extern  int * vb_transfer_1_svc();
extern int vbank_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_vb_credit_1_argument (XDR *, vb_credit_1_argument*);
extern  bool_t xdr_vb_debit_1_argument (XDR *, vb_debit_1_argument*);
extern  bool_t xdr_vb_transfer_1_argument (XDR *, vb_transfer_1_argument*);

#else /* K&R C */
extern bool_t xdr_vb_credit_1_argument ();
extern bool_t xdr_vb_debit_1_argument ();
extern bool_t xdr_vb_transfer_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_VBANK_H_RPCGEN */
